.version: 2.1


jobs:
  build-and-test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update && apt-get upgrade
      - run: echo 'export DEBIAN_FRONTEND="noninteractive"' >> $BASH_ENV 
      - run: apt-get install -y tzdata
      - run: ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - run: dpkg-reconfigure --frontend noninteractive tzdata      
      - run: apt-get install nodejs -y && apt-get install npm -y
      - run: npm install -g newman
      - run: apt-get install python3 -y && apt-get -y install python3-pip
      # - run: pip3 install pipenv
      - run: pip3 install -r requirements.txt

  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./api-test/flask_crud_collection.postman_collection.json
          environment: ./api-test/flask-crud.postman_environment.json
          timeout: '1000'

workflows:
  main:
    jobs:
      - build-and-test
      # - newman-collection-run:
      #     requires:
      #       - build-and-test