version: 2.1


jobs:
  build-and-test:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - checkout
      - run: echo "hello"
      
      # - run: pip install pipenv
      # - run: pip install -r requirements.txt
      # - run:
      #     command: pytest
      #     name: Test
      # - run: 
      #     name: "flask running"
      #     background: true
      #     command: python app.py


  # newman-collection-run:

  #   steps:
  #     - checkout
  #     - newman/newman-run:
  #         collection: ./api-test/flask_crud_collection.postman_collection.json
  #         environment: ./api-test/flask-crud.postman_environment.json
  #         timeout: '1000'

workflows:
  main:
    jobs:
      - build-and-test
      # - newman-collection-run:
      #     requires:
      #       - build-and-test